<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="tiger2"
    nsURI="http://korpling.german.hu-berlin.de/tiger2/" nsPrefix="tiger2">
  <eClassifiers xsi:type="ecore:EClass" name="Graph">
    <eOperations name="getOutgoingEdges" upperBound="-1" eType="#//Edge">
      <eParameters name="nodeId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getIncomingEdges" upperBound="-1" eType="#//Edge">
      <eParameters name="nodeId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="findNode" eType="#//SyntacticNode">
      <eParameters name="nodeId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="findEdge" eType="#//Edge">
      <eParameters name="edgeId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="findRoots" upperBound="-1" eType="#//SyntacticNode"/>
    <eOperations name="findRoot" eType="#//SyntacticNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="edges" upperBound="-1"
        eType="#//Edge" containment="true" eOpposite="#//Edge/graph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="syntacticNodes" upperBound="-1"
        eType="#//SyntacticNode" containment="true" eOpposite="#//SyntacticNode/graph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nonTerminals" upperBound="-1"
        eType="#//NonTerminal" changeable="false" volatile="true" transient="true"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="terminals" upperBound="-1"
        eType="#//Terminal" changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="segment" eType="#//Segment"
        eOpposite="#//Segment/graphs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SyntacticNode" abstract="true" eSuperTypes="#//AnnotatableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="graph" eType="#//Graph"
        eOpposite="#//Graph/syntacticNodes"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NonTerminal" eSuperTypes="#//SyntacticNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="Terminal" eSuperTypes="#//SyntacticNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" eType="#//URI"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="word" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Edge" eSuperTypes="#//AnnotatableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//SyntacticNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//SyntacticNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="graph" eType="#//Graph"
        eOpposite="#//Graph/edges"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="URI" instanceClassName="java.net.URI"/>
  <eClassifiers xsi:type="ecore:EClass" name="Segment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="graphs" upperBound="-1"
        eType="#//Graph" containment="true" eOpposite="#//Graph/segment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="corpus" eType="#//Corpus"
        eOpposite="#//Corpus/segments"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Corpus">
    <eOperations name="createAnnotation" eType="#//Annotation">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="domain" eType="#//DOMAIN"/>
      <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="findFeature" eType="#//Feature">
      <eParameters name="featureName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="domain" eType="#//DOMAIN"/>
    </eOperations>
    <eOperations name="findFeatureValue" eType="#//FeatureValue">
      <eParameters name="featureName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="featureDomain" eType="#//DOMAIN"/>
      <eParameters name="featureValueValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="findFeature" eType="#//Feature">
      <eParameters name="featureName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="domain" eType="#//DOMAIN"/>
      <eParameters name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="createAnnotation" eType="#//Annotation">
      <eParameters name="featureName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="domain" eType="#//DOMAIN"/>
      <eParameters name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="featureValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="findFeatureValue" eType="#//FeatureValue">
      <eParameters name="featureName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="domain" eType="#//DOMAIN"/>
      <eParameters name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="featureValueValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="segments" upperBound="-1"
        eType="#//Segment" containment="true" eOpposite="#//Segment/corpus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subCorpora" upperBound="-1"
        eType="#//Corpus" containment="true" eOpposite="#//Corpus/superCorpus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superCorpus" eType="#//Corpus"
        eOpposite="#//Corpus/subCorpora"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="meta" eType="#//Meta" containment="true"
        eOpposite="#//Meta/corpus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//Feature" containment="true" eOpposite="#//Feature/corpus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Meta">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="author" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="format" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="history" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="corpus" eType="#//Corpus"
        eOpposite="#//Corpus/meta"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnnotatableElement" abstract="true"
      interface="true">
    <eOperations name="findAnnotation" eType="#//Annotation">
      <eParameters name="annotationName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="annotations" upperBound="-1"
        eType="#//Annotation" eOpposite="#//Annotation/owner"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Annotation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" eType="#//AnnotatableElement"
        eOpposite="#//AnnotatableElement/annotations"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="featureRef" lowerBound="1"
        eType="#//Feature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="featureValueRef" eType="#//FeatureValue"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feature">
    <eOperations name="findFeatureValue" eType="#//FeatureValue">
      <eParameters name="featureValueValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="featureValues" upperBound="-1"
        eType="#//FeatureValue" containment="true" eOpposite="#//FeatureValue/feature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="corpus" eType="#//Corpus"
        eOpposite="#//Corpus/features"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="domain" eType="#//DOMAIN"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dcrReference" eType="#//URI"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" eType="#//Feature"
        eOpposite="#//Feature/featureValues"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dcrReference" eType="#//URI"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DOMAIN">
    <eLiterals name="T" literal="t"/>
    <eLiterals name="NT" value="1" literal="nt"/>
    <eLiterals name="EDGE" value="2" literal="edge"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DEFAULT_TYPE">
    <eLiterals name="EDGE" literal="edge"/>
    <eLiterals name="SECEDGE" value="1" literal="secedge"/>
    <eLiterals name="PRIM" value="2" literal="prim"/>
    <eLiterals name="LABEL" value="3" literal="label"/>
    <eLiterals name="SEC" value="4" literal="sec"/>
  </eClassifiers>
</ecore:EPackage>
